services:
  _defaults:
    autowire: true
    autoconfigure: true

  FluffyFactory\Bundle\UserStatsBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'